### ISSUE TITLE
Use relative units in CSS for Retina dispalys

### ISSUE THREAD

**Issue by nelsonic** [ideaq/faster#19]
The buttons/text are super small in the iOS Simulator when we use `px` as unit of measure.
![ios-sim-faster-buttons-super-small](https://cloud.githubusercontent.com/assets/194400/6727610/2a4aae08-ce1b-11e4-808e-0c2e63384c86.png)

**Comment by iteles** [comment]
I very much favour `em`s over `px`s because we're not coding for a fixed size of page any more and relative resizing makes a lot more sense than fixed measurements.

I'm still [playing around with `rem`s](https://css-tricks.com/rems-ems/) to see if anything makes me run screaming back to `em`s. If you [don't use them in media queries](http://fvsch.com/code/bugs/rem-mediaquery/) and [don't need older browser support](http://caniuse.com/#feat=rem) then they're a no brainer.

**Comment by nelsonic** [comment]
Using ems was only _partially_ effective.
I had to add a media query for the retina display:
![iphone-sim-faster-resized](https://cloud.githubusercontent.com/assets/194400/6734342/8ccf6044-ce4f-11e4-90b8-3a18a00598f0.png)
